const fs = require("node:fs/promises");
const path = require("node:path");

const OUTBOX_GUIDE_FILES = {
  startHere: "START_HERE.md",
  pastePrompt: "01_PASTE_TO_CHATGPT.md",
  uploadList: "02_UPLOAD_THESE_FILES.md",
  afterReply: "03_AFTER_CHATGPT_REPLY.md",
  manifest: "manifest.json"
};

async function writeOutboxHandoffFiles(input) {
  const paths = outboxGuidePaths(input.outboxDir);
  const replyPath = `.chatgpt-native/inbox/${input.id}/reply.md`;
  const uploadStatus = buildUploadStatus(input);

  await fs.writeFile(paths.pastePrompt, input.ask);
  await fs.writeFile(paths.startHere, buildStartHere({ ...input, paths, replyPath }));
  await fs.writeFile(paths.uploadList, buildUploadList({ ...input, uploadStatus }));
  await fs.writeFile(paths.afterReply, buildAfterReply({ ...input, replyPath }));
  await fs.writeFile(
    paths.manifest,
    JSON.stringify(buildManifest({ ...input, replyPath, uploadStatus }), null, 2)
  );

  return paths;
}

async function writeCodexReadThis(input) {
  const readmePath = path.join(input.inboxDir, "CODEX_READ_THIS.md");
  await fs.writeFile(readmePath, buildCodexReadThis(input));
  return readmePath;
}

function outboxGuidePaths(outboxDir) {
  return Object.fromEntries(
    Object.entries(OUTBOX_GUIDE_FILES).map(([key, file]) => [key, path.join(outboxDir, file)])
  );
}

function buildUploadStatus(input) {
  return {
    context: {
      file: "context.md",
      exists: true,
      group: "Recommended",
      note: "Project context, request type, included files, git status, and safety notes."
    },
    diff: {
      file: "diff.patch",
      exists: Boolean(input.diffPath),
      group: "Optional",
      note: input.diffPath ? "Current git diff for review." : "No diff was generated for this handoff."
    },
    testOutput: {
      file: "test-output.md",
      exists: Boolean(input.testOutputPath),
      group: "Optional",
      note: input.testOutputPath
        ? "Captured test output for review."
        : "No test output was generated for this handoff."
    },
    files: {
      file: "files/",
      exists: input.copiedFiles.length > 0,
      count: input.copiedFiles.length,
      group: "Optional",
      note: input.copiedFiles.length
        ? `${input.copiedFiles.length} selected source file(s).`
        : "No selected source files were copied."
    },
    screenshots: {
      file: "screenshots/",
      exists: input.copiedScreenshots.length > 0,
      count: input.copiedScreenshots.length,
      group: "Optional",
      note: input.copiedScreenshots.length
        ? `${input.copiedScreenshots.length} screenshot file(s).`
        : "No screenshots were copied."
    }
  };
}

function buildStartHere(input) {
  return `# ChatGPT handoff

This folder was generated by \`chatgpt-native-bridge\`.

Run: ${input.id}

## What to do

1. Open ChatGPT.
2. Paste the content of:

   \`${OUTBOX_GUIDE_FILES.pastePrompt}\`

3. Upload/select the files listed in:

   \`${OUTBOX_GUIDE_FILES.uploadList}\`

4. When ChatGPT finishes, copy its final answer.
5. Run:

   \`\`\`bash
   cgn done
   \`\`\`

6. Tell Codex:

   \`\`\`text
   Please read ${input.replyPath}, accept reasonable suggestions, continue local implementation, run tests, and summarize.
   \`\`\`

## Important

This tool does not automatically paste, upload, submit, scrape, or read ChatGPT output.
`;
}

function buildUploadList(input) {
  const recommended = Object.values(input.uploadStatus).filter((item) => item.group === "Recommended");
  const optional = Object.values(input.uploadStatus).filter((item) => item.group === "Optional");
  const warnings = input.warnings.length
    ? input.warnings.map((warning) => `- ${warning}`).join("\n")
    : "- None.";

  return `# Files to upload/select in ChatGPT

Upload only what is relevant. Do not upload secrets.

Run: ${input.id}

## Recommended

${formatUploadItems(recommended)}

## Optional

${formatUploadItems(optional)}

## Not included

The bridge intentionally avoids obvious secret material such as:

- \`.env\`
- private keys
- cookies
- tokens
- credentials

## Safety warnings

${warnings}
`;
}

function buildAfterReply(input) {
  return `# After ChatGPT replies

When ChatGPT finishes:

1. Copy ChatGPT's final answer.
2. Return to your terminal.
3. Run:

   \`\`\`bash
   cgn done
   \`\`\`

This imports the clipboard into:

\`${input.replyPath}\`

4. Then tell Codex:

   \`\`\`text
   You can now read ${input.replyPath}. Please accept only reasonable suggestions, continue local changes, run tests, and summarize.
   \`\`\`

## If clipboard import does not work

Save ChatGPT's answer manually as:

\`${input.replyPath}\`

Then tell Codex to read that file.
`;
}

function buildManifest(input) {
  return {
    version: 1,
    id: input.id,
    task: input.task,
    types: input.types,
    createdAt: input.createdAt,
    files: {
      startHere: OUTBOX_GUIDE_FILES.startHere,
      pastePrompt: OUTBOX_GUIDE_FILES.pastePrompt,
      uploadList: OUTBOX_GUIDE_FILES.uploadList,
      afterReply: OUTBOX_GUIDE_FILES.afterReply,
      ask: "ask.md",
      context: "context.md",
      manifest: OUTBOX_GUIDE_FILES.manifest
    },
    replyPath: input.replyPath,
    attachments: {
      context: input.uploadStatus.context.exists,
      diff: input.uploadStatus.diff.exists,
      testOutput: input.uploadStatus.testOutput.exists,
      files: {
        exists: input.uploadStatus.files.exists,
        count: input.uploadStatus.files.count
      },
      screenshots: {
        exists: input.uploadStatus.screenshots.exists,
        count: input.uploadStatus.screenshots.count
      }
    },
    warnings: input.warnings
  };
}

function buildCodexReadThis(input) {
  return `# Codex: read this after ChatGPT import

The user imported a ChatGPT reply for this handoff.

Run: ${input.id}

## Reply file

\`${input.replyPath}\`

## Your job

1. Read \`reply.md\`.
2. Identify:
   - accepted suggestions
   - rejected suggestions
   - deferred suggestions
   - risks
   - tests to run
3. Continue local implementation.
4. Run relevant tests.
5. Summarize what changed.

## Do not

- Treat ChatGPT's answer as automatically correct.
- Execute shell commands suggested by ChatGPT without checking them.
- Expand the task beyond the user's original scope.
`;
}

function formatUploadItems(items) {
  return items.map(formatUploadItem).join("\n\n");
}

function formatUploadItem(item) {
  const state = item.exists ? "Available" : "Not generated";
  const count = Number.isInteger(item.count) ? ` Count: ${item.count}.` : "";
  return `- \`${item.file}\`: ${state}.${count}\n  - ${item.note}`;
}

module.exports = {
  OUTBOX_GUIDE_FILES,
  outboxGuidePaths,
  writeCodexReadThis,
  writeOutboxHandoffFiles
};
